---

- name: Clone VM on Proxmox
  hosts: #Hosts pve-server in file inventory
  vars_files:
    - ./vars/vms.yml
  tasks:
    - name: Clone VM
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_host: "{{ api_host }}"
        api_password: "{{ api_password }}"
        clone: "{{ clone_vm }}"
        vmid: "{{ clone_vmid}}"
        newid: "{{ new_vmid }}"
        name: "{{ name_vm }}"
        node: "{{ node }}"
        storage: #Target storage for full clone.
        timeout: 1500
    - name: Update VM
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_host: "{{ api_host }}"
        api_password: "{{ api_password }}"
        node: "{{ node }}"
        vmid: "{{ new_vmid }}"
        ipconfig:
          ipconfig0: 'ip=192.168.0.1/24,gw=192.168.0.1'
        agent: enabled=1,fstrim_cloned_disks=1
        update: true
    - name: Start VM
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        vmid: "{{ new_vmid }}"
        node: "{{ node }}"
        state: started
